spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: profile-service
              uri: http://localhost:8081
              predicates:
                - Path=/profile

          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5500"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"